### ISSUE TITLE
urllib2 module has been split in Python 3 named urllib.request and urllib.error

### ISSUE THREAD

**Issue by olygoelements** [naveednajam/Little-Snitch---Rule-Groups#1]
hi naveednajam
I'm trying to test your script in flash
but some error I have can you help me
=)

if I test on python-3.7.0-macosx10.9

The urllib2 module has been split across several modules in Python 3 named urllib.request and urllib.error

when I test on python-2.7.15-macosx10.9
i have this error

Traceback (most recent call last):
  File "/Users/oly/Downloads/Little-Snitch---Rule-Groups-master 2/stevenblack_unified_hosts_V1.1.py", line 131, in <module>
    main()
  File "/Users/oly/Downloads/Little-Snitch---Rule-Groups-master 2/stevenblack_unified_hosts_V1.1.py", line 35, in main
    f_host=urllib2.urlopen(target_url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
>>>

**Comment by naveednajam** [comment]
I tested it only  in python 2.7. as per below error it seems you are not connected to internet or not able to access steven black hostfile url. Can you try to open the url in web browser and see if it is reachable. 'https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts' 

f_host=urllib2.urlopen(target_url)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)

**Comment by pgeorgan** [comment]
This solved it for me: 

https://stackoverflow.com/questions/2792650/import-error-no-module-name-urllib2

However, you'll run into another host of issues, starting with "startswith" & "endswith" (pardon the pun). If you don't want to waste a bunch of time, just compile with Python2. I can confirm it works without error.

**Comment by naveednajam** [comment]
Thanks for confirmation.
